### ISSUE TITLE
Help with moving to multibuild

### ISSUE THREAD

**Issue by ludwigschwardt** [MacPython/python-gnureadline-wheels#1]
Hi Matthew,

I would like to move to multibuild for gnureadline but have hit a minor snag... Encrypting my API key with 'travis encrypt' throws up 'data too large - consider using travis encrypt-file or travis env set'.

Am I doing the right thing? How did you get the other repos to have a secret string of the same length as the API key (but different)? My API key starts off at a length of 685 characters already...

**Comment by matthew-brett** [comment]
What is the API key you're trying to encrypt?   The one I have is for the scikit-learn Rackspace container, and it is 32 characters long.

If you just want to use the Rackspace container, here is the Rackspace container API key encrypted against your repo:

```
  secure: "gDqaQOSYt0Czcw02BMA31ghDhSmvrUEq7hY7RDKwBz7WaBavyz1GsOedQlmAMiJcoup/iqS8mKXYg0ckEm0L2B9BlFdmZECfdV79LTjTePgg/8aDOFar5bydic4RvDCdUlVOe13hGWe69/sxcDaQEvganDCV8OjOpXOpK4SKqydz8rDAQc85w/W92qQWTOFg7zn1YYRtZCmpNhELinRqRy6GUEOYvXlPZUS7o28ASfRRAWHd1qNqIBIpFNZFA0BDPDnsE1m6SsKLD7PgjnFPjPY5WUhMQTfXA235MpXS96A93z2B4QtRPdg6BKik6q9reCiWtnPfTk16sEQo8YDPtMiORJzjixCUo3wpsv+M3fTGIfLzlOhWLbRsK/HLjKHE8z2By1TkqW++F3zva+UehCUTnQMzZA17NrerNWu87XaFHrRJITqDeekx5lINBt+33jUXPWlgGBlMGtKAwgKbD+JjI+TmMXPZSvBywfM8nesQGgeey/tzFXkGuMTSNmgiPSqumkEMUq08ydllkiH62OPkEgOe4Q4+Q2hFSQNhkeXdlEY2l2PBNPzJJtAkN4tUeRUS5FKPTrpNWfsbxKTGm/1FiysZhosoPMHBFI4IneZJlf3b7b2MXVOIyhhAVlH2hsqzXVLbCs4UonTeyqvhWg6hol3xltxP70h+4lR0bjc="
```

**Comment by ludwigschwardt** [comment]
Awesome, thanks!

I was trying to use the key found under

deploy:
  api_key:
    secure: "Dt/j..."

I realise now that this was probably already an encrypted environment
variable, maybe with just a different variable name...

**Comment by ludwigschwardt** [comment]
I've finally taken the plunge and converted to multibuild and it was surprisingly painless. Thanks a lot - the above API key did the trick!
